package main

import (
	"fmt"
	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/jmoiron/sqlx"
	"github.com/midedickson/chatabase"
	"log"
)

func main() {
	dbUrl := "postgresql://postgres:root@127.0.0.1/veerge"

	db, err := sqlx.Connect("pgx", dbUrl)
	if err != nil {
		log.Fatal(err)
	}

	defer func() {
		_ = db.Close()
	}()

	chartConfigs, err := chatabase.ParseMultipleConfigs(chartConfigJsonString)
	if err != nil {
		log.Fatal(err)
	}

	for _, c := range chartConfigs {
		query, args, err := chatabase.ToSql(c)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Println(query, args)
		rows, err := db.Queryx(query, args...)
		if err != nil {
			log.Fatal(err)
		}

		// This will work regardless of how many Y-values your query returns
		data, err := chatabase.ScanDynamicChart(rows)
		if err != nil {
			log.Fatal(err)
		}

		// Access the data
		for _, row := range data {
			fmt.Printf("Date: %v\n", row.XValue)
			for i, yVal := range row.YValues {
				fmt.Printf("  Y%d: %v\n", i, yVal)
			}
		}
	}

}

var chartConfigJsonString = `
[
  {
    "chart_type": "line",
    "title": "Monthly Transaction Volume and Count",
    "description": "Transaction volume in currency and total count by month",
    "tables": [
      {
        "name": "transactions",
        "alias": "t"
      }
    ],
    "x_axis": {
      "column": "DATE_TRUNC('month', t.created_at)",
      "label": "Month",
      "data_type": "datetime",
      "format": "date"
    },
    "y_axis": [
      {
        "column": "t.amount",
        "label": "Total Volume",
        "aggregation": "SUM",
        "data_type": "numeric",
        "format": "currency"
      },
      {
        "column": "*",
        "label": "Transaction Count",
        "aggregation": "COUNT",
        "data_type": "numeric"
      }
    ],
    "group_by": ["DATE_TRUNC('month', t.created_at)"],
    "filters": [
      {
        "column": "t.status",
        "operator": "=",
        "value": "completed"
      },
      {
        "column": "t.created_at",
        "operator": ">=",
        "value": "2024-01-01"
      }
    ],
    "order_by": [
      {
        "column": "DATE_TRUNC('month', t.created_at)",
        "direction": "ASC"
      }
    ],
    "limit": 12,
    "options": {
      "width": 800,
      "height": 400,
      "theme": "light",
      "show_legend": true,
      "show_grid": true,
      "date_format": "MMM YYYY",
      "colors": ["#3B82F6", "#EF4444"]
    }
  },
  {
    "chart_type": "bar",
    "title": "Revenue by Listing Type",
    "description": "Total revenue generated by each listing type",
    "tables": [
      {
        "name": "assets",
        "alias": "a",
        "joins": [
          {
            "table": "listing_units",
            "alias": "lu",
            "type": "INNER",
            "condition": "a.listing_unit_id = lu.id"
          },
          {
            "table": "listings",
            "alias": "l",
            "type": "INNER",
            "condition": "lu.listing_id = l.id"
          },
          {
            "table": "businesses",
            "alias": "b",
            "type": "INNER",
            "condition": "l.business_id = b.id"
          }
        ]
      }
    ],
    "x_axis": {
      "column": "l.listing_type",
      "label": "Listing Type",
      "data_type": "string"
    },
    "y_axis": [
      {
        "column": "a.amount_paid",
        "label": "Total Revenue",
        "aggregation": "SUM",
        "data_type": "numeric",
        "format": "currency"
      }
    ],
    "group_by": ["l.listing_type"],
    "order_by": [
      {
        "column": "SUM(a.amount_paid)",
        "direction": "DESC"
      }
    ],
    "limit": 10,
    "options": {
      "width": 600,
      "height": 350,
      "theme": "light",
      "show_legend": false,
      "show_grid": true,
      "colors": ["#10B981"]
    }
  },
  {
    "chart_type": "pie",
    "title": "Assessment Payment Status Distribution",
    "description": "Distribution of assessment payments by status",
    "tables": [
      {
        "name": "assessment_payments",
        "alias": "ap"
      }
    ],
    "x_axis": {
      "column": "ap.status",
      "label": "Payment Status",
      "data_type": "string"
    },
    "y_axis": [
      {
        "column": "*",
        "label": "Count",
        "aggregation": "COUNT",
        "data_type": "numeric"
      }
    ],
    "group_by": ["ap.status"],
    "filters": [
      {
        "column": "ap.created_at",
        "operator": ">=",
        "value": "2024-01-01"
      }
    ],
    "order_by": [
      {
        "column": "COUNT(*)",
        "direction": "DESC"
      }
    ],
    "options": {
      "width": 500,
      "height": 500,
      "theme": "light",
      "show_legend": true,
      "colors": ["#3B82F6", "#EF4444", "#F59E0B", "#10B981"]
    }
  },
  {
    "chart_type": "bar",
    "title": "Resident Vehicle Analysis by Residence",
    "description": "Number of residents vs total vehicles per residence",
    "tables": [
      {
        "name": "residences",
        "alias": "r",
        "joins": [
          {
            "table": "residents",
            "alias": "res",
            "type": "LEFT",
            "condition": "r.id = res.residence_id"
          },
          {
            "table": "vehicles",
            "alias": "v",
            "type": "LEFT",
            "condition": "res.id = v.resident_id"
          }
        ]
      }
    ],
    "x_axis": {
      "column": "r.name",
      "label": "Residence",
      "data_type": "string"
    },
    "y_axis": [
      {
        "column": "res.id",
        "label": "Total Residents",
        "aggregation": "COUNT",
        "data_type": "numeric"
      },
      {
        "column": "v.id",
        "label": "Total Vehicles",
        "aggregation": "COUNT",
        "data_type": "numeric"
      }
    ],
    "group_by": ["r.id", "r.name"],
    "filters": [
      {
        "column": "v.deleted_at",
        "operator": "IS",
        "value": null
      }
    ],
    "order_by": [
      {
        "column": "COUNT(res.id)",
        "direction": "DESC"
      }
    ],
    "limit": 15,
    "options": {
      "width": 900,
      "height": 400,
      "theme": "light",
      "stacked": false,
      "show_legend": true,
      "show_grid": true,
      "colors": ["#8B5CF6", "#06B6D4"]
    }
  },
  {
    "chart_type": "area",
    "title": "Payment Plan Performance by Business",
    "description": "Asset purchase value vs total payments by business and plan type",
    "tables": [
      {
        "name": "assets",
        "alias": "a",
        "joins": [
          {
            "table": "payment_plans",
            "alias": "pp",
            "type": "INNER",
            "condition": "a.plan_id = pp.id"
          },
          {
            "table": "businesses",
            "alias": "b",
            "type": "INNER",
            "condition": "a.business_id = b.id"
          }
        ]
      }
    ],
    "x_axis": {
      "column": "b.business_name",
      "label": "Business",
      "data_type": "string"
    },
    "y_axis": [
      {
        "column": "a.asset_value",
        "label": "Total Asset Value",
        "aggregation": "SUM",
        "data_type": "numeric",
        "format": "currency"
      },
      {
        "column": "a.amount_paid",
        "label": "Total Amount Paid",
        "aggregation": "SUM",
        "data_type": "numeric",
        "format": "currency"
      },
      {
        "column": "pp.purchase_price",
        "label": "Total Purchase Price",
        "aggregation": "SUM",
        "data_type": "numeric",
        "format": "currency"
      }
    ],
    "group_by": ["b.id", "b.business_name"],
    "filters": [
      {
        "column": "a.status",
        "operator": "=",
        "value": "purchased"
      },
      {
        "column": "pp.deleted_at",
        "operator": "IS",
        "value": null
      }
    ],
    "order_by": [
      {
        "column": "SUM(a.asset_value)",
        "direction": "DESC"
      }
    ],
    "limit": 8,
    "options": {
      "width": 1000,
      "height": 500,
      "theme": "dark",
      "stacked": false,
      "show_legend": true,
      "show_grid": true,
      "colors": ["#F59E0B", "#10B981", "#EF4444"]
    }
  },
  {
    "chart_type": "line",
    "title": "Weekly Inspection Trends",
    "description": "Inspection requests vs approvals by week",
    "tables": [
      {
        "name": "inspections",
        "alias": "i",
        "joins": [
          {
            "table": "profiles",
            "alias": "p",
            "type": "INNER",
            "condition": "i.profile_id = p.id"
          },
          {
            "table": "businesses",
            "alias": "b",
            "type": "INNER",
            "condition": "i.business_id = b.id"
          }
        ]
      }
    ],
    "x_axis": {
      "column": "DATE_TRUNC('week', i.created_at)",
      "label": "Week",
      "data_type": "datetime",
      "format": "date"
    },
    "y_axis": [
      {
        "column": "*",
        "label": "Total Inspections",
        "aggregation": "COUNT",
        "data_type": "numeric"
      },
      {
        "column": "CASE WHEN i.status = 'accepted' THEN 1 END",
        "label": "Approved Inspections",
        "aggregation": "COUNT",
        "data_type": "numeric"
      }
    ],
    "group_by": ["DATE_TRUNC('week', i.created_at)"],
    "filters": [
      {
        "column": "i.created_at",
        "operator": "BETWEEN",
        "values": ["2024-01-01", "2024-12-31"]
      }
    ],
    "order_by": [
      {
        "column": "DATE_TRUNC('week', i.created_at)",
        "direction": "ASC"
      }
    ],
    "limit": 52,
    "options": {
      "width": 800,
      "height": 400,
      "theme": "light",
      "show_legend": true,
      "show_grid": true,
      "date_format": "MMM DD",
      "time_interval": "week",
      "colors": ["#3B82F6", "#10B981"]
    }
  },
  {
    "chart_type": "histogram",
    "title": "Currency Usage in Transactions",
    "description": "Distribution of transaction amounts by currency",
    "tables": [
      {
        "name": "transactions",
        "alias": "t",
        "joins": [
          {
            "table": "currencies",
            "alias": "c",
            "type": "INNER",
            "condition": "t.currency = c.code"
          }
        ]
      }
    ],
    "x_axis": {
      "column": "c.name",
      "label": "Currency",
      "data_type": "string"
    },
    "y_axis": [
      {
        "column": "t.amount",
        "label": "Total Amount",
        "aggregation": "SUM",
        "data_type": "numeric",
        "format": "currency"
      },
      {
        "column": "t.amount",
        "label": "Average Amount",
        "aggregation": "AVG",
        "data_type": "numeric",
        "format": "currency"
      }
    ],
    "group_by": ["c.code", "c.name"],
    "filters": [
      {
        "column": "c.active",
        "operator": "=",
        "value": true
      },
      {
        "column": "t.status",
        "operator": "=",
        "value": "completed"
      }
    ],
    "order_by": [
      {
        "column": "SUM(t.amount)",
        "direction": "DESC"
      }
    ],
    "options": {
      "width": 700,
      "height": 400,
      "theme": "light",
      "show_legend": true,
      "show_grid": true,
      "colors": ["#8B5CF6", "#F59E0B"]
    }
  },
  {
    "chart_type": "scatter",
    "title": "Request Status by Business Profile Role",
    "description": "Request completion rates by different user roles",
    "tables": [
      {
        "name": "requests",
        "alias": "r",
        "joins": [
          {
            "table": "business_profile_roles",
            "alias": "bpr",
            "type": "INNER",
            "condition": "r.profile_id = bpr.profile_id"
          },
          {
            "table": "businesses",
            "alias": "b",
            "type": "INNER",
            "condition": "bpr.business_id = b.id AND r.business_id = b.id"
          }
        ]
      }
    ],
    "x_axis": {
      "column": "bpr.role",
      "label": "User Role",
      "data_type": "string"
    },
    "y_axis": [
      {
        "column": "*",
        "label": "Total Requests",
        "aggregation": "COUNT",
        "data_type": "numeric"
      },
      {
        "column": "CASE WHEN r.status = 'approved' THEN 1 END",
        "label": "Completed Requests",
        "aggregation": "COUNT",
        "data_type": "numeric"
      }
    ],
    "group_by": ["bpr.role"],
    "filters": [
      {
        "column": "r.deleted_at",
        "operator": "IS",
        "value": null
      },
      {
        "column": "r.created_at",
        "operator": ">=",
        "value": "2024-01-01"
      }
    ],
    "order_by": [
      {
        "column": "COUNT(*)",
        "direction": "DESC"
      }
    ],
    "limit": 20,
    "options": {
      "width": 600,
      "height": 400,
      "theme": "light",
      "show_legend": true,
      "show_grid": true,
      "colors": ["#EC4899", "#14B8A6"]
    }
  }
]`
